---
version: "2"

checks:
  method-count:
    enabled: false
  argument-count:
    enabled: false

plugins:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true

exclude_patterns:
- docu/
- var/
- unittests/
- src/common/data/js/lib/
- src/common/data/css/lib/
