version: "3.7"

x-defaults: &defaults
  image: ${DOCKERIMAGE-mancelot_django}
  environment:
    DJANGO_SETTINGS_MODULE: settings
    DJANGO_ENV_FILE: .env
  volumes:
    - .:/mancelot
    - ./settings/.env:/mancelot/settings/.env:ro
    - ${MANCELOT_DATA_PATH-../data/}django/log:/mancelot/log:rw
    - ${MANCELOT_DATA_PATH-../data/}django/media:/mancelot/media:rw
    - ${MANCELOT_DATA_PATH-../data/}django/static:/mancelot/static:rw
    - ${MANCELOT_DATA_PATH-../data/}sqldumps:/sqldumps:rw
  restart: unless-stopped

services:

  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MANCELOT_MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MANCELOT_DATA_PATH-../data/}django/mariadb:/var/lib/mysql

  # Redis as broker for Celery + Cache backend for Django
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: "redis-server"

  django:
    <<: *defaults
    depends_on:
      - "redis"
      - "mariadb"
    command: ['uwsgi', '--ini', 'uwsgi/mancelot.ini']

  # Celery is a Distributed Task Queue
  celery:
    <<: *defaults
    depends_on:
      - "redis"
      - "celery_beat"
    entrypoint: "celery -E -A settings worker -c 2 -l info"

  # Celery beat is a scheduler; It kicks off tasks at regular intervals, that
  # are then executed by available worker nodes in the cluster.
  celery_beat:
    <<: *defaults
    entrypoint: "celery -A settings beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    healthcheck:
      disable: true

  # Flower to monitor Celery
  celery_flower:
    <<: *defaults
    volumes:
      - .:/mancelot
      - ./settings/.env:/mancelot/settings/.env:ro
      - ./flower.js:/usr/local/lib/python3.7/site-packages/flower/static/js/flower.js
    entrypoint: "flower -A settings --port=5555 --logging=debug"
    healthcheck:
      disable: true

networks:
  default:
    external:
      name: mancelot
