version: "2"
services:
  proxy:
    container_name: psono-quickstart-psono-proxy
    image: psono-proxy
    ports:
      - "${PSONO_EXTERNAL_PORT}:80"
    restart: always
    links:
    - psono-server:psono-quickstart-psono-server
    - psono-client:psono-quickstart-psono-server

  postgres:
    container_name: psono-quickstart-psono-postgres
    image: psono/psono-postgres:latest
    ports:
      - "${PSONO_DB_EXTERNAL_PORT}:80"
    environment:
      POSTGRES_PASSWORD: "${PSONO_POSTGRES_PASSWORD}"
    volumes:
      - ~/psono/data/postgresql:/var/lib/postgresql/data

  psono-server:
    container_name: psono-quickstart-psono-server
    image: psono/psono-server:latest
    depends_on:
      - postgres
    links:
      - postgres:psono-quickstart-psono-postgres
      - mail:psono-quickstart-psono-mail
    command: sh -c "sleep 10 && python3 psono/manage.py migrate && python3 psono/manage.py createuser demo@${PSONO_DOMAIN} demo demo@example.com && uwsgi --ini /root/configs/docker/psono_uwsgi_port.ini"
    volumes:
      - ~/psono/psono-server/password_manager_server/static/email:/var/www/html/static/email
      - ~/psono/psono-server:/root
      - ~/psono/config/settings.yaml:/root/.psono_server/settings.yaml

  psono-client:
    container_name: psono-quickstart-psono-client
    image: psono/psono-client:latest
    volumes:
      - ~/psono/psono-client/src/common/data:/usr/share/nginx/html
      - ~/psono/config/config.json:/usr/share/nginx/html/config.json

  mail:
    container_name: psono-quickstart-psono-mail
    image: digiplant/fake-smtp
    volumes:
      - ~/psono/data/mail:/var/mail
