version: "2"

services:

  db:
    build: db
    image: mancelot_psono_db:v1.9.2
    read_only: true
    restart: unless-stopped
    networks:
      - my_network
    volumes:
      - ../data/psono/db/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=psono
      - POSTGRES_PASSWORD=psono_password
      - POSTGRES_DB=psono

#  psono-server:
#    build:
#      context: psono-server
#      dockerfile: DockerfileAlpine
#    image: mancelot_psono_server:v1.9.2
#    restart: unless-stopped
#    networks:
#      - my_network
# 
#   psono-client:
#     build:
#       context: psono-client
#     image: mancelot_psono_client:v1.11.0
#     restart: unless-stopped
#     networks:
#       - my_network

networks:
  my_network:
    external: true
