version: '2'
services:
  master:
    build: .
    environment:
      - POSTGRES_USER=usernamehere
      - POSTGRES_PASSWORD=passwordhere
      - POSTGRES_REPLICATION_USER=replusernamehere
      - POSTGRES_REPLICATION_PASSWORD=replpasswordhere
      - POSTGRES_REPLICATION_MODE=master

  slave:
    build: .
    links:
      - master:master
    environment:
      - POSTGRES_USER=usernamehere
      - POSTGRES_PASSWORD=passwordhere
      - POSTGRES_REPLICATION_USER=replusernamehere
      - POSTGRES_REPLICATION_PASSWORD=replpasswordhere
      - POSTGRES_REPLICATION_MODE=slave
      - POSTGRES_REPLICATION_MASTER_HOST=master
      - POSTGRES_REPLICATION_MASTER_PORT=5432