# Generated by Django 2.2.4 on 2019-08-17 18:57

import accounts.managers
from django.db import migrations, models
import django_countries.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(help_text='First and last name', max_length=150, null=True, verbose_name='full name')),
                ('address', models.CharField(blank=True, help_text='Streetname and housenumber', max_length=128, null=True, verbose_name='address')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='zip code')),
                ('city', models.CharField(blank=True, max_length=42, null=True, verbose_name='city')),
                ('country', django_countries.fields.CountryField(blank=True, default='NL', max_length=2, null=True, verbose_name='country')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='balance')),
                ('monthly_top_up_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('monthly_top_up', djmoney.models.fields.MoneyField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='monthly top up')),
                ('payment_preference', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Bank Transfer'), (1, 'Ideal'), (2, 'Paypal')], default=None, null=True, verbose_name='payment preference')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date Laatst Gewijzigd')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', accounts.managers.AccountManager()),
            ],
        ),
    ]
