# Generated by Django 2.2.6 on 2019-11-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190817_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='favorites',
        ),
    ]
