# Generated by Django 2.2.4 on 2019-08-06 22:56

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190807_0056'),
        ('accounts', '0002_auto_20190806_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'Gebruiker', 'verbose_name_plural': 'Gebruikers'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='catalogue.Product', verbose_name='favorieten'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Straatnaam huisnummer'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='Stad'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='NL', max_length=2, null=True, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum Aangemaakt'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Datum Laatst Gewijzigd'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=42, verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(max_length=42, null=True, verbose_name='Voornaam Achternaam'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(max_length=42, verbose_name='Achternaam'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postcode'),
        ),
    ]
