# Generated by Django 2.2.6 on 2019-11-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_usermodel_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='iban',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='iban'),
        ),
    ]
