# Generated by Django 2.2.4 on 2019-08-08 20:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190808_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, help_text='Streetname and housenumber', max_length=128, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='NL', max_length=2, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(help_text='First and last name', max_length=150, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='zip code'),
        ),
    ]
