# Generated by Django 2.2.4 on 2019-08-10 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190808_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_changed_accounts', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
