# Generated by Django 2.2.4 on 2019-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=450, null=True, verbose_name='thumnail'),
        ),
    ]
