# Generated by Django 2.2.4 on 2019-08-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_thumnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cecelabel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='color',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='material',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='paymentoption',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='size',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=450, null=True, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=255, verbose_name='url'),
        ),
    ]
