# Generated by Django 2.2.4 on 2019-08-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190807_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Mannen'), (1, 'Vrouwen'), (2, 'Kinderen')], default=0, verbose_name='sectie'),
        ),
    ]
