# Generated by Django 2.2.4 on 2019-08-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20190807_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='certificate',
            new_name='certificates',
        ),
    ]
