# Generated by Django 2.2.4 on 2019-08-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20190808_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material',
            new_name='materials',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='sizes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='subcategories',
        ),
    ]
