# Generated by Django 2.2.4 on 2019-08-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20190810_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cecelabel',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='cece_api_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
