# Generated by Django 2.2.4 on 2019-08-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20190810_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='certificates',
            field=models.ManyToManyField(blank=True, related_name='brands', to='catalogue.Certificate', verbose_name='certificates'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='brands', to='catalogue.CeceLabel', verbose_name='labels'),
        ),
        migrations.AlterField(
            model_name='store',
            name='payment_options',
            field=models.ManyToManyField(related_name='stores', to='catalogue.PaymentOption', verbose_name='payment options'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalogue.Category', verbose_name='category'),
        ),
    ]
