# Generated by Django 2.2.4 on 2019-08-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20190810_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Men'), (1, 'Women'), (2, 'Kids')], default=0, verbose_name='section'),
        ),
    ]
