# Generated by Django 2.2.4 on 2019-08-10 14:53

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20190810_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AddField(
            model_name='product',
            name='from_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='from_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='EUR', help_text="Product on sale if 'from price' is given.", max_digits=19, null=True, verbose_name='from price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='EUR', max_digits=19, verbose_name='price'),
        ),
    ]
