version: "3"

services:

  db:
    build: db
    image: mattermost-db:v5.25.1
    read_only: true
    restart: unless-stopped
    volumes:
      - ${MANCELOT_DATA_PATH}mattermost/postgresql:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=$MANCELOT_MATTERMOST_POSTGRES_PASSWORD
      - POSTGRES_DB=mattermost
    container_name: mancelot_mattermost_db

  app:
    build:
      context: app
      args:
        - edition=team
        - PUID=1000
        - PGID=1000
    image: mattermost-app:v5.25.1
    restart: unless-stopped
    volumes:
      - ${MANCELOT_DATA_PATH}mattermost/config:/mattermost/config:rw
      - ${MANCELOT_DATA_PATH}mattermost/data:/mattermost/data:rw
      - ${MANCELOT_DATA_PATH}mattermost/logs:/mattermost/logs:rw
      - ${MANCELOT_DATA_PATH}mattermost/plugins:/mattermost/plugins:rw
      - ${MANCELOT_DATA_PATH}mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority (link: https://github.com/mattermost/mattermost-server/issues/13059)
      # - <path_to_your_gitlab_pki>/pki_chain.pem:/etc/ssl/certs/pki_chain.pem:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=$MANCELOT_MATTERMOST_POSTGRES_PASSWORD
      - MM_DBNAME=mattermost
    container_name: mancelot_mattermost_app

networks:
  default:
    external:
      name: mancelot
