version: "2"

services:

  db:
    build: db
    image: mancelot_mattermost_db:v5.9.0
    read_only: true
    restart: unless-stopped
    networks:
      - my_network
    volumes:
      - ../data/mattermost/db/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  app:
    build:
      context: app
      args:
        - edition=team
    image: mancelot_mattermost_app:v5.9.0
    restart: unless-stopped
    networks:
      - my_network
    volumes:
      - ../data/mattermost/config:/mattermost/config:rw
      - ../data/mattermost/data:/mattermost/data:rw
      - ../data/mattermost/logs:/mattermost/logs:rw
      - ../data/mattermost/plugins:/mattermost/plugins:rw
      - ../data/mattermost/client-plugins:/mattermost/client/plugins:rw
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
    ports:
      - "8065:8065"

networks:
  my_network:
    external: true
